export interface Member {
    mb_name: string;
    mb_surname: string;
    mb_birthday: number;
    mb_gender: string;
    mb_nick: string;
    mb_email: string;
    mb_phone: string;
    mb_password: string;
    mb_type:string;
    mb_status:string;
    mb_address?: string;
    mb_description?: string;
    mb_country?: string;
    mb_profile_image?: string;
    mb_background_image?: string;
    mb_views: number;
    mb_likes: number;
    mb_notification: number;
    mb_follow_count: number;
    mb_subscriber_count: number;
};